site_name: MeteoMarche Documentation
theme:
  name: readthedocs
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'it'
  features:
    - navigation
    - meta
    - cover
    - feature
    - footer
    - code-highlighting
    - search
    - toc
    - tabs
    - favicon
    - share
    - footer
    - extra
    - include
    - sitemap
    - authors
    - logo
    - social
    - theme-color
    - typography
